### PR TITLE
Major refactoring and additions of many `Base` methods

### PR DESCRIPTION
**Pull request by bicycle1885**
Summary:
* The `readbytes!` method is no longer an extended method of `Base`; it is now a new method of `BufferedStreams` module.
* Rename `EmptyStreamSource` to `EmptyStream` since it can be a sink.
* Add `Base.`{`mark`, `unmark`, `ismarked`, `rest`} methods for buffered input streams.
* Make `close(stream)` close the underlying I/O object.
* Make `close(stream)` release the allocated buffer.
* Add and fix tests for v0.5 compatibility.

### CODE REVIEW

**Comment by Ward9250** [comment]
This looks like some good stuff @bicycle1885! Does it need a rebase?

**Comment by bicycle1885** [comment]
Yes, it does. I already did the rebase locally and now I'm fixing the decreased coverage.

**Comment by bicycle1885** [comment]
I will merge this today if no objections.

**Comment by Ward9250** [comment]
I heartily say :shipit: !

**Comment by bicycle1885** [comment]
Thank you! Yes, I will tag and release a new version soon. It would be a minor version update because this is not just a bugfix.

**Pull request merged**
