### PR TITLE
work around test failute on v0.5-dev (#20)

### PR DESCRIPTION
**Pull request by bicycle1885**
Seems to be related to https://github.com/JuliaLang/julia/issues/17170.

### CODE REVIEW

**Comment by tkelman** [comment]
Huh? Because `position` is used as a function name somewhere else maybe? Very odd, sounds like a bug.

(Why isn't Travis running here?)

**Comment by bicycle1885** [comment]
The behavior is unpredictable to me. So, I renamed all `position` variables that may collide with `Base.position` to `p`. I think this should be fixed in the upstream.

I don't know why Travis won't run. Maybe I need to kick off it again.

**Comment by tkelman** [comment]
try closing and reopening the issue? that works for me sometimes

**Comment by bicycle1885** [comment]
@tkelman Thanks. Nice tips.

**Comment by bicycle1885** [comment]
The great decrease of code coverage would be not related to this pull request.

**Comment by tkelman** [comment]
This hasn't been tagged yet, has it?

**Comment by bicycle1885** [comment]
Not yet. I'll tag it soon.

**Comment by tkelman** [comment]
thanks. oh, and did the issue get reported on base julia? was it equivalent to something already open?

**Comment by bicycle1885** [comment]
Yes, I guess this is the same: https://github.com/JuliaLang/julia/issues/17170.

**Pull request merged**
